## games_details 데이터셋에 대해 EDA 실행

In [1]:
from utils import CustomDataset

In [2]:
games_details = CustomDataset('games_details')
games_details.load()

games_details.data.head(10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
5,22200477,1610612759,SAS,San Antonio,1628380,Zach Collins,Zach,NaN,NaN,18:04,...,1.0,1.0,2.0,2.0,0.0,0.0,0.0,3.0,6.0,-13.0
6,22200477,1610612759,SAS,San Antonio,203926,Doug McDermott,Doug,NaN,NaN,16:55,...,1.0,3.0,4.0,1.0,0.0,0.0,1.0,0.0,5.0,-10.0
7,22200477,1610612759,SAS,San Antonio,1626196,Josh Richardson,Josh,NaN,NaN,21:20,...,1.0,2.0,3.0,3.0,0.0,0.0,1.0,2.0,14.0,-2.0
8,22200477,1610612759,SAS,San Antonio,1631103,Malaki Branham,Malaki,NaN,NaN,21:10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,9.0,-6.0
9,22200477,1610612759,SAS,San Antonio,1628966,Keita Bates-Diop,Keita,NaN,NaN,9:16,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,-1.0

In [3]:
games_details.version_msg

['raw']

In [4]:
games_details.preprocess(drop=True)
games_details.data

,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,1629641,Romeo Langford,Romeo,F,NaN,18:06,1.0,1.0,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,7.0,14.0,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,6.0,9.0,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,1630170,Devin Vassell,Devin,G,NaN,30:20,4.0,13.0,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,1630200,Tre Jones,Tre,G,NaN,27:44,7.0,12.0,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668623,11200005,1610612743,202706,Jordan Hamilton,NaN,NaN,NaN,19,4.0,9.0,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN
668624,11200005,1610612743,202702,Kenneth Faried,NaN,NaN,NaN,23,7.0,11.0,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN
668625,11200005,1610612743,201585,Kosta Koufos,NaN,NaN,NaN,15,3.0,7.0,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN
668626,11200005,1610612743,202389,Timofey Mozgov,NaN,NaN,NaN,19,1.0,1.0,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN
668627,11200005,1610612743,201951,Ty Lawson,NaN,NaN,NaN,27,3.0,6.0,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN

In [8]:
preprocessed_data = games_details.data.copy()

In [12]:
preprocessed_data.groupby('PLAYER_NAME').agg({'PLAYER_ID': 'nunique'}).sort_values('PLAYER_ID', ascending=False)

                       PLAYER_ID
PLAYER_NAME
Josh Davis                     3
Wesley Matthews                3
Chris Johnson                  2
Brian Skinner                  2
Deonte Burton                  2
...                          ...
Glenn Robinson III             1
Goga Bitadze                   1
Goran Dragic                   1
Goran Suton                    1
Giannis Antetokounmpo          1

[2664 rows x 1 columns]

In [16]:
player_filtered = preprocessed_data[preprocessed_data['PLAYER_NAME'] == 'Chris Johnson']
player_filtered[['PLAYER_ID']].drop_duplicates()

        PLAYER_ID
312718     202419
482561     203187

In [20]:
player_filtered.dropna(subset='START_POSITION')

,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
337257,21001227,1610612757,202419,Chris Johnson,NaN,F,NaN,40:19,1.0,8.0,...,8.0,5.0,13.0,1.0,1.0,1.0,2.0,4.0,8.0,-20.0
531008,21500958,1610612762,203187,Chris Johnson,NaN,G,NaN,19:30,2.0,4.0,...,1.0,2.0,3.0,0.0,1.0,0.0,2.0,2.0,5.0,-1.0
541064,21500555,1610612762,203187,Chris Johnson,NaN,G,NaN,31:02,6.0,9.0,...,0.0,4.0,4.0,3.0,2.0,2.0,2.0,5.0,14.0,22.0
591707,21400023,1610612755,203187,Chris Johnson,NaN,G,NaN,29:18,1.0,11.0,...,2.0,6.0,8.0,0.0,0.0,1.0,1.0,1.0,4.0,-1.0
592168,21400005,1610612755,203187,Chris Johnson,NaN,F,NaN,32:12,5.0,10.0,...,0.0,1.0,1.0,1.0,1.0,0.0,2.0,1.0,12.0,1.0
592654,11400109,1610612755,203187,Chris Johnson,NaN,G,NaN,31:13,5.0,13.0,...,0.0,4.0,4.0,2.0,0.0,0.0,2.0,0.0,15.0,-6.0

# 과제: 가장 최근 날짜의 아이디로 통합해야 함.
# 동명이인의 가능성?
https://stats.nba.com/stats/playerindex?College=&Country=&DraftPick=&DraftRound=&DraftYear=&Height=&Historical=1&LeagueID=00&Season=2025-26&SeasonType=Preseason&TeamID=0&Weight=
1. 동명이인 O
- Chris Johnson
- Steven Smith
- Marcus Williams
- Tony Mitchell
- Glen Rice
- Chris Smith
- Dee Brown (3명)
- Chris Wright
- Brandon Williams
- Mike James
- Justin Hamilton
2. 동명이인 X
- Josh Davis
- Wesley Matthews
- Brian Skinner
- Deonte Burton
- Justin Williams
- Brian Hamilton (정보 검색 안됨)
- Dionte Christmas
- Georges Niang
- Tristan Thompson
- Chris Crawford
- Josh Akognon
- Andre Brown
- Gerry McNamara (정보 검색 안됨)
- Gabe Muoneke (정보 검색 안됨)
- Jan Vesely
- Damien Wilkins
- Jamar Smith (정보 검색 안됨)
- Vernon Macklin

-> 그냥 ID로 하고 불러올 때 NAME 쓰자.